### PR TITLE
This can be considered a "test" pull request. Very minor change.

### PR DESCRIPTION
**Pull request by joey711**
Since this is also imported elsewhere in the package, this doesn't
change the package behavior, but I did happen to miss the import when I
was "borrowing" tree.layout for my own package.
# ' @importFrom plyr rbind.fil

I don't think this affects the NAMESPACE file for now, unless the other
function that uses this, tree.as.data.frame, is removed or has this
dependency tag removed.

Very minor change, but thought I'd see how the pull request goes :)

As a side-note, very soon I'll be integrating some of the ggphylo code
into phyloseq, attributing you as author and linking to this repo.

### CODE REVIEW

**Comment by joey711** [comment]
Since this is really minor, I could just click the "Merge pull request" button myself, but I'll leave it for you to accept/reject as a "test run" pretending it was actually a more important change I wanted you to see and/or discuss. I don't think I've sent a pull request to someone else's repo before. Pretty cool.

**Comment by gjuggler** [comment]
Hey Joey, thanks for sending along this "test" request! This all seems pretty easy to use, I hadn't done collab github development like this before so it's nice to see.

**Comment by joey711** [comment]
Awesome. I was hoping it was that easy. I similarly had not done collab devel on github yet. So far so good!

**Comment by joey711** [comment]
Hey Gregory,

FYI, the latest devel version of [phyloseq](https://github.com/joey711/phyloseq/) has some of your code as internal functions supporting the new `plot_tree()` command. You can checkout the documentation that cites you (and give comment if you want), it is here:

[plot_tree doc](https://github.com/joey711/phyloseq/blob/master/man/plot_tree.Rd)

And if you're interested in the source, it is consolidated within the [plot-methods.R](https://github.com/joey711/phyloseq/blob/master/R/plot-methods.R) file.

**Comment by joey711** [comment]
Also, `plot_tree` now has a wiki page with code and examples, in case you are interested:

https://github.com/joey711/phyloseq/wiki/plot_tree

**Pull request merged**
